name: ViewInv
version: ${project.version}
main: author404e.viewinv.ViewInv
api-version: 1.16
authors: [ 404E ,xbaimiao ]
depend: [ AmazingBot ]
commands:
  vi:
    description: 插件主命令
    usage: /<command>
  viewinv:
    description: 插件主命令
    usage: /<command>
permissions:
  viewinv.admin:
    default: op
